export const projects = [
  {
    title: 'EJ Job Application',
    description: 'AI-powered job application platform built with Flutter. Features smart resume matching, automated cover letter generation, and intelligent job recommendations.',
    tags: ['Flutter', 'Dart', 'AI/ML', 'Firebase', 'REST API'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: 'https://e-job-application-ai-powered.netlify.app/',
    featured: true,
  },
  {
    title: 'ShopEase Mobile',
    description: 'Cross-platform e-commerce app with Flutter. Features real-time product catalog, Stripe payments, push notifications, and offline cart functionality.',
    tags: ['Flutter', 'Dart', 'Firebase', 'Stripe', 'BLoC'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: true,
  },
  {
    title: 'FitTrack Pro',
    description: 'Health and fitness tracking app built with Flutter. Tracks workouts, nutrition, sleep patterns with beautiful charts and health data sync.',
    tags: ['Flutter', 'Dart', 'Health API', 'SQLite', 'Charts'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: true,
  },
  {
    title: 'ChatConnect',
    description: 'Real-time messaging app with Flutter and Firebase. Features end-to-end encryption, voice messages, file sharing, and group chats.',
    tags: ['Flutter', 'Dart', 'Firebase', 'WebRTC', 'Riverpod'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
  {
    title: 'TaskMaster',
    description: 'Productivity and task management app with Flutter. Features Kanban boards, reminders, time tracking, and team collaboration.',
    tags: ['Flutter', 'Dart', 'Hive', 'Local Notifications', 'BLoC'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
  {
    title: 'WeatherWise',
    description: 'Beautiful weather app with Flutter featuring real-time forecasts, animated weather conditions, and location-based alerts.',
    tags: ['Flutter', 'Dart', 'OpenWeather API', 'Animations', 'Provider'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
  {
    title: 'ExpenseTracker',
    description: 'Personal finance app built with Flutter. Track expenses, set budgets, visualize spending patterns with interactive charts.',
    tags: ['Flutter', 'Dart', 'SQLite', 'Charts', 'GetX'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
  {
    title: 'EventHub',
    description: 'Event booking and management app with Flutter. Browse events, book tickets, get QR passes, and receive event reminders.',
    tags: ['Flutter', 'Dart', 'Firebase', 'QR Code', 'Google Maps'],
    iconType: 'mobile',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
  {
    title: 'Portfolio Website',
    description: 'Personal portfolio website built with Next.js and Tailwind CSS. Features smooth animations, responsive design, and dark mode.',
    tags: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'Framer Motion'],
    iconType: 'web',
    github: 'https://github.com/xavihachem',
    demo: '#',
    featured: false,
  },
] as const

export const projectGradients = [
  'from-violet-500 via-purple-500 to-fuchsia-500',
  'from-cyan-500 via-blue-500 to-indigo-500',
  'from-emerald-500 via-teal-500 to-cyan-500',
  'from-orange-500 via-amber-500 to-yellow-500',
  'from-rose-500 via-pink-500 to-purple-500',
  'from-indigo-500 via-violet-500 to-purple-500',
  'from-teal-500 via-emerald-500 to-green-500',
  'from-blue-500 via-cyan-500 to-teal-500',
] as const

export const projectIcons: { [key: string]: string } = {
  web: 'Globe',
  mobile: 'Smartphone',
  ai: 'Cpu',
  fullstack: 'Layers',
  database: 'Database',
  creative: 'Sparkles',
  startup: 'Rocket',
  security: 'Shield',
}
